package com.itsm.smartitsm.common.enums;

/**
 * 通知类型枚举
 */
public enum NotificationTypeEnum {

    TICKET_ASSIGNED,
    TICKET_ACCEPTED,
    TICKET_TRANSFERRED,
    TICKET_COMMENTED,
    TICKET_COLLABORATION,
    TICKET_RESOLVED,
    TICKET_REJECTED,
    TICKET_CLOSED,
    TICKET_CANCELLED,
    TICKET_NUDGE,
    TICKET_ESCALATED,
    SLA_WARNING,
    SLA_BREACHED,
    TRANSFER_REQUEST_RECEIVED,
    TRANSFER_REQUEST_APPROVED,
    TRANSFER_REQUEST_REJECTED,
    TRANSFER_REQUEST_CANCELLED
}
